# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 12:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('duration', models.IntegerField()),
                ('interest_rate', models.FloatField()),
                ('collateral_worth', models.FloatField()),
                ('date_applied', models.DateTimeField()),
                ('approval_status', models.CharField(choices=[('A', 'Approved'), ('D', 'Denied'), ('P', 'Pending')], default='P', max_length=1)),
                ('date_granted', models.DateTimeField(blank=True)),
                ('repay_amount', models.FloatField()),
                ('date_due', models.DateTimeField(blank=True)),
                ('repayment_status', models.CharField(choices=[('R', 'Repaid'), ('N', 'Not repaid'), ('D', 'Defaulted')], default='N', max_length=1)),
                ('date_repaid', models.DateTimeField(blank=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
