# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_amount', models.FloatField()),
                ('max_amount', models.FloatField()),
                ('min_duration', models.IntegerField()),
                ('max_duration', models.IntegerField()),
                ('interest_rate', models.FloatField()),
            ],
        ),
    ]
